nspcc-dev/neofs-api

README.md
There is a shiny brand new readme file for new repository structure. It contains links for the language-specific repositories and gives brief description about protobuf packages.
=> docs: Update readme file for public release

container/types.proto
=> [#20] Add attributes in container definition

acl/types.proto, container/service.proto, container/types.proto, proto-docs/acl.md, proto-docs/container.md
This is an example of large PR with several issues solved. 
Pull request resolves #21, resolves #22 and resolves #23. 
Includes:
- EACLTable message in EACL related requests,
- signature fields in container requests,
- removing unused fields such as meta request header and verify request header.
=> Update container package to v2

accounting/service.proto, acl/types.proto, container/service.proto, container/types.proto, netmap/types.proto, object/service.proto, object/types.proto, proto-docs/accounting.md, proto-docs/acl.md, proto-docs/container.md, proto-docs/netmap.md, proto-docs/object.md, proto-docs/refs.md, proto-docs/service.md, proto-docs/session.md, proto-docs/storagegroup.md, refs/types.proto, service/meta.proto, service/verify.proto, session/service.proto, storagegroup/types.proto
Trying to be more friendly and follow common style.
Related issues: #32
=> Rename message fields according to Protobuf Style Guide

accounting/service.proto, acl/types.proto, container/service.proto, container/types.proto, netmap/types.proto, object/service.proto, object/types.proto, refs/types.proto, service/meta.proto, service/verify.proto, session/service.proto, storagegroup/types.proto
=> Reindent according to Google Style Guide

acl/types.proto, object/service.proto, object/types.proto, proto-docs/acl.md, proto-docs/object.md
- Trying to move enums to the package level
- Trying to keep all definitions in types.proto
=> Minor reformat

netmap/types.proto, object/service.proto, proto-docs/netmap.md
Proposed protobuf format for Placement Policy simplifies direct editing in visual editors and import/export from other formats like JSON.
=> Simplify Placement Policy

acl/types.proto, proto-docs/acl.md
Fixes #61 and minor naming mismatched between Protobuf and JSON.
=> Add Version field to eECL Table and fix naming issues

netmap/types.proto, proto-docs/netmap.md
Helps to define how selection is formed
=> Add SAME|DISTINCT selector clause

.github/workflows/dco.yml
Make GH Actions to check if there are commits with no `Signed-off-by` in PR.
=> Add simple DCO check

.github/workflows/dco.yml
DCO check  action can be used with PRs only.
=> Fix wrong DCO action config

.github/workflows/buf.yml
Just run `buf` linter and check if there are breaking changes.
=> Add GH Action for protobuf linter

acl/types.proto
=> Add clarification for BearerToken.body.owner_id

container/types.proto, object/types.proto
Resolves nspcc-dev/neofs-api-go#172
=> Add more well-known attributes

object/types.proto
=> Mention object split limitation by type

acl/types.proto
Change does not break JSON compatibility.
=> acl: Add json_name notation to EACLTable.Version field

acl/types.proto, object/service.proto, object/types.proto, session/types.proto
With recent split process clarifications there are few things to fix.
=> Update object split mechanisms

audit/types.proto, proto-docs/audit.md
Inner ring nodes conduct data audit and submit audit results. Results are then saved in audit smart contract for settlement routines to transfer payments.
We don't need to save the full detailed audit report, but only provide enough information for other subsystems to reward or punish storage nodes.
Closes: #109
=> Define data audit result structure

audit/types.proto, proto-docs/audit.md
Add PoR stats to DataAuditResult
=> Add PoR stats to DataAuditResult

CHANGELOG.md
Signed-off-by: Leonard Lyubich <leonard@nspcc.ru>
=> Update changelog for v2.2.1

container/service.proto
This method will be used in P2P communication between nodes so they can estimate average container load.
=> container: Add AnnounceUsedSpace method

object/service.proto, object/types.proto
=> object: Define NOT_PRESENT value in MatchType enum

netmap/service.proto, netmap/types.proto
=> Add rpc to read information about NeoFS network

reputation/service.proto, reputation/types.proto
=> Add proto definitions of Reputation service

reputation/service.proto, reputation/types.proto
=> reputation: Add SendIntermediateResult RPC

reputation/service.proto, reputation/types.proto
=> Change trust type in reputation.SendIntermediateResult

container/service.proto, session/types.proto
=> Support container sessions

netmap/types.proto, proto-docs/netmap.md
Closes #160.
In #160 we decided to break JSON format.
=> netmap: Provide the ability to announce multiple addresses

object/types.proto, proto-docs/object.md
=> Feat/Add `COMMON_PREFIX` matchtype to object

netmap/types.proto
=> Expand netmap.NetworkInfo

netmap/types.proto, proto-docs/netmap.md
=> Doc/Add subnet attributes to `NodeInfo`

session/types.proto, status/types.proto
=> Pass sidechain magic in requests

status/types.proto
=> Add detail with correct network magic

container/service.proto, proto-docs/container.md, proto-docs/refs.md, refs/types.proto
=> [#55] refs: add signature scheme description

CONTRIBUTING.md, README.md, accounting/service.proto, accounting/types.proto, acl/types.proto, audit/types.proto, container/service.proto, container/types.proto, doc/release_instructions.md, lock/types.proto, netmap/service.proto, netmap/types.proto, object/service.proto, object/types.proto, refs/types.proto, reputation/service.proto, reputation/types.proto, session/service.proto, session/types.proto, status/types.proto, storagegroup/types.proto, tombstone/types.proto
Checked for some inaccuracies regarding English.
Signed-off-by: Elizaveta Chichindaeva <elizaveta@nspcc.ru>
=> English Check

object/service.proto, status/types.proto
=> [#208] status: Add `OUT_OF_RANGE` status in Object section

acl/types.proto
Signed-off-by: anastasia prasolova <anastasia@nspcc.ru>
=> Comments fix for ACL

netmap/types.proto, status/types.proto
=> Maintenance node state and status code

object/service.proto
Description of statuses sorted by sections and codes looks more logical.
Signed-off-by: Leonard Lyubich <leonard@nspcc.ru>
* closes #198
=> [#198] object: Sort statuses by codes

session/types.proto
=> [#202] session: Support group object sessions

netmap/types.proto
=> netmap: Define keys of `NetworkConfig.Parameter`

object/service.proto, proto-docs/object.md
A helper for the new split scheme from the
a825a7ecd07725cbb9caa37f2181c7aa8e285fc2.
=> object/search: Add first child filter

accounting/service.proto, container/service.proto, netmap/service.proto, netmap/types.proto, object/service.proto, proto-docs/accounting.md, proto-docs/container.md, proto-docs/netmap.md, proto-docs/object.md
=> *: get rid of "sidechain"

proto-docs/refs.md, refs/types.proto
no options in terms of the wire protocol. I gonna hold it for now to improve docs after server implementation proposal
=> Support Neo N3 auth scheme

CHANGELOG.md, object/service.proto, proto-docs/object.md, proto-docs/status.md, status/types.proto
Refs https://github.com/nspcc-dev/neofs-node/issues/3520.
=> status: add PUT deny status on exceeding limits
