- README.md
- acl/types.proto
- proto-docs/acl.md
Basic NeoFS ACL applies access rules to request sender. Request
senders are combined in groups that calls `targets`.
Basic ACL rules may be applied to these targets:
1. User - request sender is the owner of the container,
used in the request.
2. System - request sender is the storage node
within the container used in the request or
inner ring node.
3. Others - request sender is none of the above.
Extended ACL rules may be applied for targets, provided with
extra information.
4. PubKey - request sender has provided public key.
> acl: Define target of access control rules 

- container/service.proto
- container/types.proto
- proto-docs/container.md
With new ACL conception, access control lists in NeoFS defined as a required **basic ACL** and optional **extended ACL**.
Basic ACL must be set up in container structure. It is a bit mask stored in 32-bit unsigned integer.
Seven nibbles represent seven object operations: 
- get,
- put,
- head,
- search,
- delete,
- range,
- range-hash.
Every nibble defines access rules for three targets: **user**, **owner**, **others** and has permission bit for **bearer token**.
There is a permission bit for extended ACL and three unused bits.
> container: Replace `AccessGroup` with `BasicACL

- Makefile
- proto-docs/object.md
- proto-docs/state.md
- state/service.proto
The main objective of this method is to allow to control and manage the state of the node by its owner.
- if the user is not declared in the settings, the system returns an access error.
- if the new status is not defined or is not known, the system notifies about that.
- if the new status is known to the system, it will be applied and the node will change the current status.
> Add gRPC method to change current node state

- object/service.proto
- proto-docs/object.md
Session token is presented in RequestVerificationHeader, therefore its presence in request bodies is redundant.
> object: remove Token field from PutRequest.PutHeader and DeleteRequest

- proto-docs/service.md
- service/verify.proto
This commit:
* removes gogoproto customname option from embedded Token.Info field;
* renames Info field of Token message to TokenInfo.
> service: remove gogoproto customname from embedded Token.Info field

- proto-docs/service.md
- proto-docs/session.md
- service/verify.proto
- session/service.proto
Summary:
- put token lifetime to a separate message;
- make `Session.Create` RPC to be unary message;
- make `session.CreateRequest` message to carry owner ID and token lifetime;
- make `session.CreateResponse` message to carry token ID and public session key.
> Change Session.Create RPC

- proto-docs/service.md
- service/verify.proto
`OwnerKey` field of `Token.TokenInfo` message is going to be used for quick access to the public key of the owner.
> service: add OwnerKey byte field to TokenInfo message

- accounting/service.proto
- proto-docs/accounting.md
Remove MetaHeader and VerifyHeader from balance request as these fields are also
removed from all container related requests.
Signed-off-by: Stanislav Bogatyrev <stanislav@nspcc.ru>
> [#33] Remove unused headers

- object/types.proto
- proto-docs/object.md
- proto-docs/service.md
- service/verify.proto
In the current version of the format, a session token is issued to a specific address of an object, which creates an inseparable connection between sessions and object operations. To unify the session mechanism, it is required to abstract the token from the object.
Change `Token.Info.address` field of type `refs.Address` with `oneof` enumeration of session contexts. In the initial version, only the object context is available. Additional contexts can be added without losing backward compatibility.
> Session token context

- accounting/service.proto
- container/service.proto
- object/service.proto
- session/service.proto
Body messages divide requests and responses into payload scope and transport-meta scope, which include meta header and signatures. NeoFS nodes and clients can verify transmission via transport-meta scope and then work only with payload scope, that stored in `body` field of the request.
Merge this PR when transport-meta-scope of `ResponseVerificationHeader` and `ResponseMetaHeader` will be ready.
> Add body messages to API requests

- netmap/types.proto
- object/service.proto
- proto-docs/accounting.md
- proto-docs/container.md
- proto-docs/object.md
- proto-docs/service.md
- proto-docs/session.md
- service/meta.proto
- service/verify.proto
For the cases when we need to relay a request between several nodes, we need to have a mechanism to record message path in a verifiable manner. The proposed solution is to recursively add signed request/response meta information on each hop.
> Add Matryoshka-style request and response headers

- proto-docs/service.md
- service/meta.proto
- service/verify.proto
If we allow all types of requests to be forwarded between nodes, it would require additional context included in SessionToken. For now we have only ObjectService request forwarding, but in future we may add more.
> Add per-service context to SessionToken

- accounting/service.proto
- acl/types.proto
- container/service.proto
- container/types.proto
- netmap/types.proto
- object/service.proto
- object/types.proto
- refs/types.proto
- service/meta.proto
- service/verify.proto
- session/service.proto
- storagegroup/types.proto
To simplify adding more transport level protocols to `neofs-api-go` in future, we need to separate currently default gRPC.
> Add grpc suffix to go_package option

- container/types.proto
- object/types.proto
- proto-docs/container.md
- proto-docs/object.md
Some pieces of data (container, object, etc) may be stored for a long time and
there will be a need in the future to understand which obscure format from the
past was used to create it.
> Add version fields where it makes sense

- object/service.proto
- object/types.proto
- refs/types.proto
- storagegroup/types.proto
NeoFS uses different checksum algorithms. It looks like we need to explicitly define what algorithm is used in each particular case.
> Add separate checksum type

- netmap/types.proto
- proto-docs/netmap.md
To simplify decoding of NodeInfo structure inside netmap smart contract, the first field, also used as a storage key inside contract, has to be of the fixed length.
> Put NodeInfo public_key field first

- netmap/service.proto
- proto-docs/netmap.md
This should be used as a handshake to know API Version supported by peer and to update local netmap view in future.
> Add LocalNodeInfo request

- object/service.proto
Object.Head method returns either full header or short header. Since it can't return anything else, signature must be paired with full header in explicit tuple message.
> Use tuple of full header and signature at object head response body

- acl/types.proto
- object/service.proto
- object/types.proto
Describing a way to access not only object attributes, but also specific header fields.
> Clarify object search and ACL filters header references

- acl/types.proto
- object/service.proto
- proto-docs/acl.md
- proto-docs/container.md
- proto-docs/object.md
Make object search and ACL filters use the same field names, as they are used for the very similar functionality.
> Rename object search and ACL filters fields for consistency

- acl/types.proto
- object/service.proto
Extended ACL description lacks `objectID` key in filters. It's useful to control access to specific object.
Closes: #87
> Add object ID key in extended ACL filters

- object/service.proto
It's expected by app developers that this filter will return the list of objects created by user, without supplementary objects like split object parts, tombstones and storage groups.
ref: nspcc-dev/neofs-node#151
> Clarify $Object:ROOT filter description

- object/service.proto
- object/types.proto
SplitInfo structure from split_info field contains meta information to assembly the object that has been split into parts.
> Add split_info field in object.GetResponse body

- container/types.proto
- netmap/types.proto
- object/types.proto
In case there is a need to set flag-like attributes, the value should be set to something like `true` or `1`.
Closes: #86
> Clarify that Attributes can't have empty values

- object/service.proto
- tombstone/types.proto
- Define payload structure for Tombstone object type.
- Return address of the created TS on object delete. Useful for testing
Closes #51
> Define Tombstone type and return it's address on object delete

- container/types.proto
- netmap/types.proto
- object/types.proto
All types of attribute keys must be unique and can't be repeated in the same entity.
- Containers with duplicated attribute keys must not be accepted by InnerRing on creation.
- Nodes with duplicated attribute keys can't be accepted to NetMap by InnerRing
- Objects with duplicated attribute keys must be considered invalid and not accepted in PUT operations
Closes #81
> Clarify that attribute names must be unique

- refs/types.proto
It may be confusing to findout that JSON-encoded protobuf `bytes` are base64 encoded and it's not the same format as String representation.
> Clarify JSON encoding for OID, CID and OwnerID

- acl/types.proto
Related: nspcc-dev/neofs-node#247
> Clarify object field usage in some requests' eACL filters

- object/types.proto
Hashes in ShortHeader are needed for Data Audit process.
Closes: #110
> Add hashes to ShortHeader structure

- audit/types.proto
- proto-docs/audit.md
The `version` field required for having IR nodes with different software versions working together.
The `complete` flag needed for marking audits that didn't finish because of time out or some other reasons. The exact reason should be written in Audit Report separately.
> Add version and complete flag

- session/service.proto
- session/types.proto
When object can't be found using current network map, there is a chance to find it using netmap versions from previous epochs.
By default only current netmap is used. Well-known X-Headers can be used to set the specific netmap version and limit how deep into the past the node can go in the search of an object.
Closes #117
> Describe well-known X-Headers

- container/service.proto
Nodes aggregate size estimation based on container id and epoch number. Estimations are not valid forever.
> Add epoch field to container size announcement

- object/service.proto
According to the given need https://github.com/nspcc-dev/neofs-api-go/issues/255 object search filters must support strict JSON format. This need originally appeared in https://github.com/nspcc-dev/neofs-node/issues/362. There are two possible solutions:
1. use CLI-specific JSON format
2. use API JSON format (as expected in https://github.com/nspcc-dev/neofs-api-go/issues/255)
To solve the problem in method 2, it is required to explicitly set the `json_name` field tags.
> object: Add json_name tags to fields of SearchRequest.Body.Filter

- netmap/types.proto
UN/LOCODE-relate node attributes:
- `UN-LOCODE` (ex `Locode`)
- `CountryCode` (new)
- `Country` (existing, documentation update may be required)
- `LocationCode` (new)
- `Location` (seems like `City`)
- `SubDivCode` (new)
- `SubDiv` (seems like `Region`)
-  `Continent` (new)
@realloc, please, help me to write the documentation for new attributes. N.B.:
- update `UN-LOCODE` doc if needed
- update `Country` doc if needed
- replace `City` with `Location` if needed, otherwise reconsider `City`
- replace `Region` with `SubDiv` if needed, otherwise reconsider `Region`
> Extend list of node attributes with UN/LOCODE-related attributes

- doc/release_instructions.md
We need release instructions to use them as a check-list at release creation time.
> Add release instructions

- tombstone/types.proto
Expiration epoch value should be the same in tombstone object body and in tombstone object header.
> Same expiration epoch value in tombstone body and header

- object/service.proto
It may be confusing for the user to get all types of objects as the result of a search with no filters set. Human users may expect to see only the objects intended for direct manipulation by humans.
> Clarify empty search filter behaviour

- object/types.proto
- proto-docs/object.md
Neo3 Oracles need a way to check object's MIME content type, as described in neo-project/neo-modules#555.
The proposal was to add Content-Type as a well-known attribute.
Closes #141
> Add well-known attribute for content type

- reputation/types.proto
Add `version` field as a first field of `GlobalTrust` message. This field
will allow you to quickly extract the version of the message from the binary
representation.
Additionally fix `signature` field's package format.
Related to #143.
> reputation: Add version field to GlobalTrust message

- acl/types.proto
Service headers are ignored by NeoFS nodes but can be
used to save access-related information by services
built on top of NeoFS.
> acl: add filter for service headers

- session/types.proto
Closes #82.
Please note that a new header field has been added before the origin field, although it has a higher ordinal number. In my opinion, this order will make it easier to understand the structure of the header.
> session: Add sidechain magic to RequestMetaHeader

- accounting/service.proto
- container/service.proto
- netmap/service.proto
- object/service.proto
- proto-docs/accounting.md
- proto-docs/acl.md
- proto-docs/container.md
- proto-docs/netmap.md
- proto-docs/object.md
- proto-docs/reputation.md
- proto-docs/session.md
- proto-docs/status.md
- reputation/service.proto
- session/service.proto
- session/types.proto
- status/types.proto
Related #150.
Docs will be added right after structural finalization.
> Introduce response status errors

- netmap/types.proto
- refs/types.proto
> netmap: add subnet id to placement policy

- proto-docs/status.md
- status/types.proto
Close #189, #190, #191.
1. I am not sure whether ACL-related codes should be in the Object, Container or a separate ACL section. `object.Put` acl denied seems to belong to container service, while `object.Get` is related to a specific object.
2. Prefixes are somewhat ugly IMO but necessary because of name conflicts. May be we should prefix all enum values with the service name.
3. We can also define service specific errors in related packages, which helps us with (2). Here I define them in one package.
> Add status codes for object, container and session services.

- container/service.proto
- lock/types.proto
- object/service.proto
- object/types.proto
- proto-docs/container.md
- proto-docs/lock.md
- proto-docs/object.md
- proto-docs/status.md
- status/types.proto
> object: Add `LOCK` type

- CHANGELOG.md
- container/service.proto
- proto-docs/container.md
- proto-docs/refs.md
- refs/types.proto
Remove `UNSPECIFIED` value from `SignatureScheme` enum. Make
`ECDSA_SHA512` to be default signature scheme (zero value).
Define `SignatureRFC6979` type for RFC-6979 signatures. Use it in
`Container` service.
Signed-off-by: Leonard Lyubich <leonard@nspcc.ru>
> refs: Change support for different signature schemes

- object/service.proto
Minor clarification to show how XHeaders should be used.
> Clarification for eXtended Headers in MetaHeader

- proto-docs/storagegroup.md
- storagegroup/types.proto
To avoid ambiguity, let's use the common well-known attribute to control both Object and Storage Group expirations.
This change affects the whole stack, including Storage and Inner Ring nodes logic. Should be merged only when we are ready to change implementation.
> Use well-known expiration attribute for SGs

- refs/types.proto
I will update the comment when the reference document is there.
> refs: add WalletConnect signature type

- container/service.proto
- proto-docs/container.md
- proto-docs/status.md
- status/types.proto
> Feat/Add `EACL_NOT_FOUND` status

- netmap/service.proto
- netmap/types.proto
Clients need an easy way of getting network map to get connection endpoints form Node's attributes.
Related: nspcc-dev/neofs-sdk-go#297
> Add netmap snapshot request

- object/types.proto
FilePath attribute is already used by S3 and HTTP protocol gateways.
Also seen in [Gaspump](https://github.com/configwizard/gaspump-api/), NeoFS.Send and NeoFS.CDN.
Closes: #238
> Add FilePath object attribute

- netmap/types.proto
The task says "external" but wouldn't "internal" be better here? I mean for backwards compatibility we have a single address to which user connects and optional internal addresses to use for storage nodes.
> Add a well-known attribute for additional addresses

- netmap/types.proto
- proto-docs/netmap.md
_Inspired by https://github.com/nspcc-dev/neofs-node/issues/2280_
> netmap: Add reserved node attribute for verified nodes' domain

- object/service.proto
- proto-docs/object.md
here is a design of the separate object replication API
in addition to general simplification, the main motivation is to reduce amount of transmitted service data (request headers, signatures, stream markup, etc.) compared to general purpose `rpc Put`
> object: Separate API for node-to-node replication

- CHANGELOG.md
- object/service.proto
- object/types.proto
- proto-docs/object.md
Previously, protocol did not support numerical search queries for objects. This may be needed for system attributes such as payload size or creation epoch, and for user ones if required by the client application.
New values of `MatchType` enumeration are added: `>`, `>=`, `<`, `<=`. These attributes allow user to search for objects with any decimal attributes. While only base-10 numbers are allowed, additional bases may be supported in the future without new enumerations
Note that the previously added `STRING_EQUAL` / `STRING_NOT_EQUAL` matchers are suitable for numerical `==` / `!=`.
Closes #265.
> object: Support numerical search queries

- object/service.proto
- proto-docs/object.md
* see also https://github.com/nspcc-dev/neofs-sdk-go/pull/565
> object: Switch to object ID signature in `Replicate` request

- proto-docs/refs.md
- refs/types.proto
i propose to reserve zero IDs and prohibit them from being message fields. While this is a breaking change in theory, in practice nothing will break. At the same time, application development will benefit
> refs: Prohibit IDs consisting of all zero bytes

- acl/types.proto
- proto-docs/acl.md
> Extend Target comment for ACL

- object/service.proto
- proto-docs/object.md
I am not sure about `create` naming.
> object/replicate: Add signature to the replication RPC

- object/service.proto
- proto-docs/object.md
Covers both RANGE and RANGEHASH, fixes #313.
> object: specify 0:0 range requests as special

- README.md
- accounting/service.proto
- accounting/types.proto
- acl/types.proto
- audit/types.proto
- container/service.proto
- container/types.proto
- link/types.proto
- lock/types.proto
- netmap/service.proto
- netmap/types.proto
- object/service.proto
- object/types.proto
- proto-docs/acl.md
- proto-docs/object.md
- proto-docs/session.md
- proto-docs/tombstone.md
- refs/types.proto
- reputation/service.proto
- reputation/types.proto
- session/service.proto
- session/types.proto
- status/types.proto
- storagegroup/types.proto
- subnet/types.proto
- tombstone/types.proto
These just follow whatever happens now in implementation, no real changes.
> Documentation improvements

- container/types.proto
- netmap/types.proto
- object/types.proto
- proto-docs/container.md
- proto-docs/netmap.md
- proto-docs/object.md
While technically this is a valid UTF-8 character in practice:
* it's a string terminator in C and some software can help problems with it
* we'd like to use it for internal purposes when working with DBs, it's a very convenient separator
* no one uses it and no one should be using it
> *: forbid zero byte in attributes

- object/service.proto
- object/types.proto
- proto-docs/object.md
Its usage is unknown, current official implementations do not support and do not expect it.
> object: deprecate ShortHeader

- lock/types.proto
- object/types.proto
- proto-docs/lock.md
- proto-docs/object.md
- proto-docs/tombstone.md
- tombstone/types.proto
It obsoletes old LOCK- and TOMBSTONE-typed objects with strictly typed messages in their payloads. Closes #312, closes #311.
> object: add `__NEOFS__ASSOCIATE` object attribute

- audit/types.proto
- object/types.proto
- proto-docs/audit.md
- proto-docs/object.md
- proto-docs/storagegroup.md
- storagegroup/types.proto
Both are totally unused, we better create another mechanism for this in future. Refs. https://github.com/nspcc-dev/neofs-node/issues/3442.
> *: deprecate audit and storage groups
